### ISSUE TITLE
Thread Merge Error

### ISSUE THREAD

**Issue by ielm** [quickwit-oss/tantivy-cli#86]
When running through the wiki indexing tutorial, I keep getting the following error - regardless of multi- or single-thread. I am on WSL on an Intel I9-13900K. 

```
 ○ cat wiki-articles.json | tantivy index -i ./wiki
65523 Docs
235882816 docs / hour 78.24 Mb/s
101293 Docs
128397080 docs / hour 49.50 Mb/s
145485 Docs
159090880 docs / hour 69.63 Mb/s
181873 Docs
120802736 docs / hour 52.18 Mb/s
227277 Docs
163452752 docs / hour 61.36 Mb/s
264562 Docs
121315152 docs / hour 77.24 Mb/s
281652 Docs
61521108 docs / hour 84.31 Mb/s
297545 Docs
57208676 docs / hour 44.33 Mb/s
thread 'merge_thread_0' panicked at 'Logic Error in Tantivy (Please report). Facet field should have required a`term_ordinal_mapping`.', /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.19.0/src/indexer/merger.rs:262:48
stack backtrace:
   0:     0x565357daacf3 - std::backtrace_rs::backtrace::libunwind::trace::he615646ea344481f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x565357daacf3 - std::backtrace_rs::backtrace::trace_unsynchronized::h6ea8eaac68705b9c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x565357daacf3 - std::sys_common::backtrace::_print_fmt::h7ac486a935ce0bf7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x565357daacf3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1b5a095d3db2e28f
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x565357cba50e - core::fmt::write::h445545b92224a1cd
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/fmt/mod.rs:1209:17
   5:     0x565357d847e4 - std::io::Write::write_fmt::h55a43474c6520b00
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/io/mod.rs:1682:15
   6:     0x565357dabfcf - std::sys_common::backtrace::_print::h65d20526fdb736b0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x565357dabfcf - std::sys_common::backtrace::print::h6555fbe12a1cc41b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x565357dabbcf - std::panicking::default_hook::{{closure}}::hbdf58083140e7ac6
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:267:22
   9:     0x565357dacc68 - std::panicking::default_hook::haef8271c56b74d85
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:286:9
  10:     0x565357dacc68 - std::panicking::rust_panic_with_hook::hfd45b6b6c12d9fa5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:688:13
  11:     0x565357dac732 - std::panicking::begin_panic_handler::{{closure}}::hf591e8609a75bd4b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:579:13
  12:     0x565357dac69c - std::sys_common::backtrace::__rust_end_short_backtrace::h81899558795e4ff7
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x565357dac671 - rust_begin_unwind
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
  14:     0x565357bd1492 - core::panicking::panic_fmt::h4235fa9b4675b332
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
  15:     0x565357cbe830 - core::panicking::panic_display::h29316b4d8276b58d
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:139:5
  16:     0x565357cbe7db - core::panicking::panic_str::hdb14547b30ece385
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:123:5
  17:     0x565357bd1606 - core::option::expect_failed::h1c9d589f6e6349ed
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/option.rs:1879:5
  18:     0x565357e3c4eb - core::option::Option<T>::expect::h90c32df798761fb3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/option.rs:741:21
  19:     0x565357e3c4eb - tantivy::indexer::merger::IndexMerger::write_fast_fields::h172e81bd94b084c9
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.19.0/src/indexer/merger.rs:262:48
  20:     0x565357e3c4eb - tantivy::indexer::merger::IndexMerger::write::h5fe7bf5b003800f5
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.19.0/src/indexer/merger.rs:1044:9
  21:     0x565357e923f7 - tantivy::indexer::segment_updater::merge::h862fa030ede427f4
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.19.0/src/indexer/segment_updater.rs:126:20
  22:     0x565357e923f7 - tantivy::indexer::segment_updater::SegmentUpdater::start_merge::{{closure}}::hc441b8015b7d0d6e
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.19.0/src/indexer/segment_updater.rs:520:19
  23:     0x565357e923f7 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h254358538d0e53d8
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panic/unwind_safe.rs:271:9
  24:     0x565357dd9a99 - std::panicking::try::do_call::h64870ef1c7a730c2
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  25:     0x565357dd9a99 - std::panicking::try::h9603a79a35137070
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  26:     0x565357dd9a99 - std::panic::catch_unwind::h38c3b0ccd1c1d895
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  27:     0x565357dd9a99 - rayon_core::unwind::halt_unwinding::he06f952ab153d619
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.1/src/unwind.rs:17:5
  28:     0x565357dd9a99 - rayon_core::registry::Registry::catch_unwind::h064d2137f6238c00
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.1/src/registry.rs:335:27
  29:     0x565357dd9a99 - rayon_core::spawn::spawn_job::{{closure}}::h138c7f51fcfa6197
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.1/src/spawn/mod.rs:97:13
  30:     0x565357dd9a99 - <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute::h0f869ba85dee0982
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.1/src/job.rs:163:9
  31:     0x565357bd6ffa - rayon_core::job::JobRef::execute::h91fb3c5f9c51df7d
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.1/src/job.rs:58:9
  32:     0x565357bd6ffa - rayon_core::registry::WorkerThread::execute::he04f598845442008
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.1/src/registry.rs:804:9
  33:     0x565357bd6ffa - rayon_core::registry::WorkerThread::wait_until_cold::hb69082dd664ee9e1
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.1/src/registry.rs:781:17
  34:     0x565357cfd18c - rayon_core::registry::WorkerThread::wait_until::hf0637ef37b4e32b9
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.1/src/registry.rs:755:13
  35:     0x565357cfd18c - rayon_core::registry::main_loop::h1670fc76fc3ad382
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.1/src/registry.rs:889:5
  36:     0x565357cfd18c - rayon_core::registry::ThreadBuilder::run::h12e761e1159afda7
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.1/src/registry.rs:53:18
  37:     0x565357cfd18c - <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}::h25c1c5b7dbd15b13
                               at /home/ielm/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.1/src/registry.rs:98:20
  38:     0x565357cfd18c - std::sys_common::backtrace::__rust_begin_short_backtrace::h8b37295483e7d1ad
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys_common/backtrace.rs:121:18
  39:     0x565357cff5a5 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h05654c7e3a46641c
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/thread/mod.rs:551:17
  40:     0x565357cff5a5 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7c1a298f02a6b896
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panic/unwind_safe.rs:271:9
  41:     0x565357cff5a5 - std::panicking::try::do_call::h8db3226a983be2e8
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:483:40
  42:     0x565357cff5a5 - std::panicking::try::hc07a5a5c73a94da3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:447:19
  43:     0x565357cff5a5 - std::panic::catch_unwind::heab44d0a4e39ab1b
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panic.rs:137:14
  44:     0x565357cff5a5 - std::thread::Builder::spawn_unchecked_::{{closure}}::h63788cda0c8357da
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/thread/mod.rs:550:30
  45:     0x565357cff5a5 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h46e072364d33c7ec
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  46:     0x565357dae135 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4273f95ec44459b3
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  47:     0x565357dae135 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70f28fa4ddc269e5
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:1987:9
  48:     0x565357dae135 - std::sys::unix::thread::Thread::new::thread_start::h85a9c16b988e2bd0
                               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/sys/unix/thread.rs:108:17
  49:     0x7fb973b88609 - start_thread
  50:     0x7fb973958133 - clone
  51:                0x0 - <unknown>
Rayon: detected unexpected panic; aborting
[1]    5023 broken pipe  cat wiki-articles.json |
       5024 abort        tantivy index -i ./wiki
```

**Comment by remram44** [comment]
Running into the same thing.

<details><summary>Schema</summary>

```
[
  {
    "name": "id",
    "type": "text",
    "options": {
      "stored": true,
      "fast": true
    }
  },
  {
    "name": "body",
    "type": "text",
    "options": {
      "indexing": {
        "record": "position",
        "fieldnorms": true,
        "tokenizer": "en_stem"
      },
      "stored": false,
      "fast": false
    }
  }
]
```
</details>

<details><summary>Backtrace</summary>

```
thread 'merge_thread_0' panicked at 'Logic Error in Tantivy (Please report). Facet field should have required a`term_ordinal_mapping`.', /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.19.2/src/indexer/merger.rs:262:48
stack backtrace:
33919 Docs
2626938 docs / hour 32.66 Mb/s
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:1880:5
   5: core::option::Option<T>::expect
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:738:21
   6: tantivy::indexer::merger::IndexMerger::write_fast_fields
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.19.2/src/indexer/merger.rs:262:48
   7: tantivy::indexer::merger::IndexMerger::write
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.19.2/src/indexer/merger.rs:1044:9
   8: tantivy::indexer::segment_updater::merge
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.19.2/src/indexer/segment_updater.rs:126:20
   9: tantivy::indexer::segment_updater::SegmentUpdater::start_merge::{{closure}}
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/tantivy-0.19.2/src/indexer/segment_updater.rs:520:19
  10: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panic/unwind_safe.rs:271:9
  11: std::panicking::try::do_call
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  12: std::panicking::try
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  13: std::panic::catch_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  14: rayon_core::unwind::halt_unwinding
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.2/src/unwind.rs:17:5
  15: rayon_core::registry::Registry::catch_unwind
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.2/src/registry.rs:335:27
  16: rayon_core::spawn::spawn_job::{{closure}}
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.2/src/spawn/mod.rs:97:13
  17: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.2/src/job.rs:163:9
  18: rayon_core::job::JobRef::execute
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.2/src/job.rs:58:9
  19: rayon_core::registry::WorkerThread::execute
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.2/src/registry.rs:804:9
  20: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.2/src/registry.rs:781:17
  21: rayon_core::registry::WorkerThread::wait_until
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.2/src/registry.rs:755:13
  22: rayon_core::registry::main_loop
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.2/src/registry.rs:889:5
  23: rayon_core::registry::ThreadBuilder::run
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.2/src/registry.rs:53:18
  24: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}
             at /home/remram/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.10.2/src/registry.rs:98:20
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Rayon: detected unexpected panic; aborting
Aborted (core dumped)
```
</details>

**Comment by PSeitz** [comment]
Looking at the code, I think this can happen if the text field is not indexed. In that case no mapping is created during merge (which is required for the fast field). This logic will be completely re-hauled for the next release.

Can you retry with enabled indexing on the text field?
```
[
  {
    "name": "id",
    "type": "text",
    "options": {
      "stored": true,
      "fast": true,
      "indexing": {
        "record": "basic"
      },
    },
  }
..
]


```

**Comment by remram44** [comment]
That fixed it for me
